GET http://localhost:3000/user

###

POST http://localhost:3000/user
Content-Type: application/json

{ "user_name": "vsc ", "email": "8888@kcc.com", "status": 0 }

###

DELETE http://localhost:3000/user/18

###

PATCH http://localhost:3000/user/1
Content-Type: application/json

{ "user_name": "zigg 3x", "email": "zigg@tada.sk" }
